name: Deploy Frontend
on:
  push:
    branches: [ "deploy" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Actualizado a v4
      - name: Docker Login
        uses: docker/login-action@v3 # Actualizado a v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }} # [cite: 3]
      - name: Build and Push
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/innovatech-frontend:latest .
          docker push ${{ secrets.DOCKER_USER }}/innovatech-frontend:latest
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/app && cd ~/app
            export DOCKER_USER=${{ secrets.DOCKER_USER }}
            export BACKEND_HOST_PRIVATE_IP=${{ secrets.BACKEND_HOST_PRIVATE_IP }}
            docker-compose pull
            docker-compose up -d --build

#commit n3 prueba confi